steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: bash
  env:
  - REGION=${_REGION}
  - BUCKET=${_BUCKET}
  args:
  - -c
  - |
    gcloud run deploy docs-ilegal-api \
      --source ./api \
      --region "$REGION" \
      --allow-unauthenticated \
      --update-env-vars BUCKET_NAME="$BUCKET"

substitutions:
  _REGION: europe-west1
  _BUCKET: docs-ilegal-uploads-466632346058  # schimbă dacă ai alt bucket

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"
